version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: server
    ports:
      - 8080:80
    volumes:
      - www:/var/www/docker-lamp-php-5

  db:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=warguilds
      - MYSQL_DATABASE=warguilds
      - MYSQL_USER=warguilds
      - MYSQL_PASSWORD=warguilds
    ports:
      - 8306:3306
    volumes:
      - /var/lib/mysql/warguilds:/var/lib/mysql/warguilds